/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.editor.outline.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Bug326937TestLanguageUiModule extends org.eclipse.xtext.ui.tests.editor.outline.ui.AbstractBug326937TestLanguageUiModule {
	public Bug326937TestLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
