/*
* generated by Xtext
*/
package org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.xtext.ui.tests.editor.outline.services.Bug326937TestLanguageGrammarAccess;

public class Bug326937TestLanguageParser extends AbstractContentAssistParser {
	
	@Inject
	private Bug326937TestLanguageGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist.antlr.internal.InternalBug326937TestLanguageParser createParser() {
		org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist.antlr.internal.InternalBug326937TestLanguageParser result = new org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist.antlr.internal.InternalBug326937TestLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAorBAccess().getAlternatives(), "rule__AorB__Alternatives");
					put(grammarAccess.getAAccess().getGroup(), "rule__A__Group__0");
					put(grammarAccess.getAAccess().getGroup_2(), "rule__A__Group_2__0");
					put(grammarAccess.getBAccess().getGroup(), "rule__B__Group__0");
					put(grammarAccess.getAAccess().getNameAssignment_1(), "rule__A__NameAssignment_1");
					put(grammarAccess.getAAccess().getContentsAssignment_2_1(), "rule__A__ContentsAssignment_2_1");
					put(grammarAccess.getBAccess().getNameAssignment_1(), "rule__B__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist.antlr.internal.InternalBug326937TestLanguageParser typedParser = (org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist.antlr.internal.InternalBug326937TestLanguageParser) parser;
			typedParser.entryRuleA();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Bug326937TestLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Bug326937TestLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
