/*
* generated by Xtext
*/
package org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist;

import org.eclipse.xtext.ui.tests.editor.outline.ui.contentassist.AbstractBug326937TestLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Bug326937TestLanguageProposalProvider extends AbstractBug326937TestLanguageProposalProvider {

}
