/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.editor.outline;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Bug326937TestLanguageRuntimeModule extends org.eclipse.xtext.ui.tests.editor.outline.AbstractBug326937TestLanguageRuntimeModule {

}
