/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.outline.Bug326937TestLanguage with org.eclipse.xtext.common.Terminals

generate bug326937TestLanguage "http://www.eclipse.org/2010/xtext/ui/tests/Bug326937TestLanguage"
 
A:
  'A' name=ID ('{' contents+=AorB* '}')?;

AorB:
	A | B;
	
B:
	'B' name=ID;