/*
* generated by Xtext
*/
package org.eclipse.xtext.xbase.ui.outline;

import org.eclipse.xtext.ui.editor.outline.old.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class XbaseTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
