<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug326937TestLanguage"
    nsURI="http://www.eclipse.org/2010/xtext/ui/tests/Bug326937TestLanguage" nsPrefix="bug326937TestLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//AorB">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//AorB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AorB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//AorB"/>
</ecore:EPackage>
